import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :apodornot_web, ApodornotWebWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :apodornot_web, ApodornotWebWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # /healthz is hit by Fly's internal health checker via plain HTTP on
      # the machine's private IP — it doesn't go through Fly's edge proxy
      # and so doesn't have :x_forwarded_proto. Without this exclusion the
      # redirect-to-HTTPS turns the health check into a 301 and the machine
      # never reaches the "healthy" state.
      paths: ["/healthz"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
